---
title: "Building R Packages - Assignment"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Building R Packages - Assignment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette provides details about a set of functions created to analyse, tabulate and visualise fatality data from the NHTSA.

Three functions are *helper* functions which will not be visable to the end user in the final version of this package:

- fars_read()
- make_filename()
- fars_read_years()

Two further functions allow a user to tabulate and visualise fatality data on a map:

- fars_summarize_years()
- fars_map_state()

For more details on each function use ?function()

## Helper functions

###fars_read()

fars_read() takes a *filename* as input and outputs a dataframe.

###make_filename()

make_filename() takes a year as input and uses this to generate a filename.

###fars_read_years()

Takes a vector of years as input and outputs a dataframe containing unique combinations of year and month values.

## Analysis functions

###fars_summarize_years()

Takes a vector of years as input and generates a table of counts of fatalities by month, for each year.

###fars_map_state()

Takes a state number and year as input and generates a map of fatalities for the chosen parameters.

